version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:12.9.0-buster

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-{{ arch }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install retry command
          command: |
            ./.circleci/setup-retry.sh
      - run:
          name: Install Chromium
          command: |
            apt update -q -y
            apt install -q -y chromium
      - run:
          name: Install dependencies
          command: retry -- yarn
      - run:
          name: Build
          command: retry -- yarn run build
      - run:
          name: Test
          command: retry -- yarn test
      - save_cache:
          key: v1-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
